#!/usr/bin/env ruby
require 'net/http'
require 'json'

DICESERV_URL = 'http://diceserv.herokuapp.com'

class DiceRoll
  # blah blah
  attr_reader :expression, :results, :rolls, :error

  def initialize expression
    @expression = expression
    @results = []
    @rolls = RollAccumulator.new
    perform
  end

  def perform
    roll_result.each do |roll_set|
      if roll_set['error']
        @error = "#{roll_set['name']}: #{roll_set['message']}"
        break
      end
      results << roll_set['result']
      rolls << RollAccumulator.new(roll_set['rolls'])
    end
  end

  def roll_result
    params = {roll: expression}
    result = Net::HTTP.post_form URI.parse(DICESERV_URL+'/roll'), params
    JSON::parse result.body
  end

  def to_s
    error or "#{expression} --> {#{results.join ', '}}#{rolls}"
  end

end

class RollAccumulator
  attr_reader :rolls

  def initialize rolls = []
    @rolls = rolls.map { |roll| Roll.new roll }
  end

  def << other
    other.rolls.each { |roll| rolls << roll }
  end

  def empty?
    rolls.empty?
  end

  def to_s
    empty? ? '' : " [ #{rolls.map(&:to_s).join ', '} ]"
  end
end

class Roll
  attr_reader :dice, :sides, :result

  def initialize roll_hash
    @dice = roll_hash['dice']
    @sides = roll_hash['sides']
    @result = roll_hash['result']
  end

  def to_s
    "#{dice}d#{sides} = #{result}"
  end
end

if __FILE__ == $0
  ARGV.each { |expr| puts DiceRoll.new expr }
end
